description: Collect shell config related files.
version: 1.0
artifacts:
  -
    description: Collect shell config files.
    collector: file
    supported_os: [all]
    path: /%user_home%
    name_pattern: [".*_login", ".*_logout", ".*_profile", ".*rc", ".cshdirs", ".ksh", ".login", ".logout", ".profile", ".tcsh", ".zlogin", ".zlogout", ".zprofile", ".zshenv"]
    max_depth: 2