version: 1.0
artifacts:
  -
    description: Display all applications located at /Applications directory.
    supported_os: [macos]
    collector: command
    command: ls -l -a /Applications
    output_file: ls_-l_-a_Applications.txt
  -
    description: Display all applications located at /Users/%user%/Applications directory.
    supported_os: [macos]
    collector: command
    command: ls -l -a /%user_home%/Applications
    output_file: ls_-l_-a_%user_home%_Applications.txt
  -
    description: Display all applications located at /Users/%user%/Applications directory.
    supported_os: [macos]
    collector: command
    command: brew list
    output_file: brew_list_%user_home%_Applications.txt
    
