description: Run and collect ifconfig command output.
version: 1.0
artifacts:
  -
    description: Collect information about all interfaces which are currently available, even if down.
    supported_os: [all]
    collector: command
    command: ifconfig -a
    output_file: ifconfig_-a.txt