description: Run and collect chkconfig command output.
version: 1.0
artifacts:
  -
    description: Display a list of all services and their current configuration.
    collector: command
    supported_os: [linux]
    command: chkconfig --list
    output_file: chkconfig_--list.txt
  