name: Deploy VM and Run Tests

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      unit_test_operating_system:
        required: true
        type: string
      unit_test_system_arch:
        required: true
        type: string
      unit_test_username:
        required: true
        type: string
      unit_test_hostname:
        required: true
        type: string
      uac_destination_dir:
        required: true
        type: string
      vagrant_box_name:
        required: true
        type: string
      vagrant_ssh_options:
        required: true
        type: string

jobs:

  run-tests:

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - name: Create testing profile
        run: |
          printf %b "name: test\ndescription: test\nartifacts:\n  - live_response/process/ps.yaml\n  - live_response/storage/*\n  - !live_response/storage/fs_usage.yaml" >uac/profiles/test.yaml

      - name: Clone uac-unit-test repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac-unit-test
          path: uac-unit-test
          ref: main

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
      
      - name: Start ${{ inputs.vagrant_box_name }} VM
        run: |
          vagrant init ${{ inputs.vagrant_box_name }}
          vagrant up

      - name: Transfer uac to VM
        run: vagrant upload uac uac

      - name: Transfer uac-unit-test to VM
        run: vagrant upload uac-unit-test uac-unit-test

      - name: Run uname -a
        run: vagrant ssh -c "uname -a"

      - name: Run id
        run: vagrant ssh -c "id"

      - name: Run unit test
        run: vagrant ssh -c "cd uac-unit-test && ./run_test ../uac ${{ inputs.unit_test_operating_system }} ${{ inputs.unit_test_system_arch }} ${{ inputs.unit_test_username }} ${{ inputs.unit_test_hostname }} tests/*"

      - name: Run sudo ./uac -p test ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && sudo ./uac -p test ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}
