name: Deploy VM and Run Tests

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      unit_test_operating_system:
        required: true
        type: string
      unit_test_system_arch:
        required: true
        type: string
      unit_test_hostname:
        required: true
        type: string
      uac_destination_dir:
        required: true
        type: string
      vagrant_box_name:
        required: true
        type: string
      vagrant_ssh_username:
        required: true
        type: string
      vagrant_ssh_password:
        required: true
        type: string
      vagrant_ssh_options:
        required: true
        type: string

jobs:

  run-tests:

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - name: Create testing profile
        run: |
          printf %b "name: test\ndescription: test\nartifacts:\n  - live_response/process/ps.yaml\n  - live_response/storage/*\n  - !live_response/storage/fs_usage.yaml" >uac/profiles/test.yaml

      - name: Clone uac-unit-test repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac-unit-test
          path: uac-unit-test
          ref: main

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
      
      - name: Create Vagrantfile
        run: |
          cat << EOF >Vagrantfile
          Vagrant.configure("2") do |config|
            config.vm.box = "${{ inputs.vagrant_box_name }}"
            config.ssh.username = "${{ inputs.vagrant_ssh_username }}"
            config.ssh.shell = "/bin/sh"
            config.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--usb", "off"]
              vb.customize ["modifyvm", :id, "--usbehci", "off"]
            end
            config.vm.synced_folder '.', '/vagrant', disabled: true
          EOF

      - name: Update Vagrantfile
        if: ${{ inputs.vagrant_ssh_password != '' }}
        run: |
          cat << EOF >>Vagrantfile
            config.ssh.password = "${{ inputs.vagrant_ssh_password }}"
          EOF

      - name: Close Vagrantfile
        run: |
          cat << EOF >>Vagrantfile
          end
          EOF

      - name: Print Vagrantfile
        run: cat Vagrantfile

      - name: Start ${{ inputs.vagrant_box_name }} VM
        run: vagrant up

      - name: Transfer uac to VM
        run: vagrant upload uac uac

      - name: Transfer uac-unit-test to VM
        run: vagrant upload uac-unit-test uac-unit-test

      - name: Run uname -a
        run: vagrant ssh -c "uname -a"

      - name: Run unit test
        run: vagrant ssh -c "cd uac-unit-test && ./run_test ../uac ${{ inputs.unit_test_operating_system }} ${{ inputs.unit_test_system_arch }} ${{ inputs.vagrant_ssh_username }} ${{ inputs.unit_test_hostname }} tests/*"

      - name: Run ./uac -p test --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -p test --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -p test -a files/system/etc.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -p test -a files/system/etc.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}
      
      - name: Run ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}
      
      - name: Run ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml,\!live_response/process/strings_running_processes.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml,\!live_response/process/strings_running_processes.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a files/logs/var_log.yaml --run-as-non-root --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a files/logs/var_log.yaml --run-as-non-root --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a files/logs/var_log.yaml --run-as-non-root --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a files/logs/var_log.yaml --run-as-non-root --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a live_response/process/ps.yaml --run-as-non-root --hostname uac-test-vm ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml --run-as-non-root --hostname uac-test-vm ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac -a live_response/process/ps.yaml --run-as-non-root --case-number 12345 --description "Case Description" --evidence-number 10 --examiner "Examiner Name" --notes "Case Notes" ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml --run-as-non-root --case-number 12345 --description \"Case Description\" --evidence-number 10 --examiner \"Examiner Name\" --notes \"Case Notes\" ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: run ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml
        run: vagrant ssh -c "cd uac && ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml" -- ${{ inputs.vagrant_ssh_options }}
