name: Deploy VM and Run Tests

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      unit_test_operating_system:
        required: true
        type: string
      unit_test_system_arch:
        required: true
        type: string
      unit_test_username:
        required: true
        type: string
      unit_test_hostname:
        required: true
        type: string
      uac_destination_dir:
        required: true
        type: string
      vagrant_box_name:
        required: true
        type: string
      vagrant_ssh_options:
        required: true
        type: string

jobs:

  run-uac-unit-test:

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - name: Clone uac-unit-test repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac-unit-test
          path: uac-unit-test
          ref: main

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
      
      - name: Start ${{ inputs.operating_system }} VM
        run: |
          vagrant init ${{ inputs.vagrant_box_name }}
          vagrant up

      - name: Transfer uac to VM
        run: vagrant upload uac uac

      - name: Transfer uac-unit-test to VM
        run: vagrant upload uac-unit-test uac-unit-test

      - name: Run uname -a
        run: vagrant ssh -c "uname -a"

      - name: Run id
        run: vagrant ssh -c "id"

      - name: Run unit test
        run: vagrant ssh -c "cd uac-unit-test && ./run_test ../uac ${{ inputs.unit_test_operating_system }} ${{ inputs.unit_test_system_arch }} ${{ inputs.unit_test_username }} ${{ inputs.unit_test_hostname }} tests/*"

  run-uac:
    needs: run-uac-unit-test

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ inputs.vagrant_box_name }}
      
      - name: Start ${{ inputs.vagrant_box_name }} VM
        run: |
          vagrant init ${{ inputs.vagrant_box_name }}
          vagrant up

      - name: Transfer uac to VM
        run: vagrant upload uac uac

      #- name: Run sudo ./uac -p ir_triage ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -p ir_triage ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run sudo ./uac -p ir_triage -a files/applications/viminfo.yaml ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -p ir_triage -a files/applications/viminfo.yaml ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run sudo ./uac -a live_response/process/ps.yaml ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/ps.yaml ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}
      
      #- name: Run sudo ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}
      
      #- name: Run sudo ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run ./uac -a live_response/process/ps.yaml -u ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/ps.yaml -u ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run sudo ./uac -a files/logs/\*,\!files/logs/additional_logs.yaml --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a files/logs/\*,\!files/logs/additional_logs.yaml --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run sudo ./uac -a files/logs/\*,\!files/logs/additional_logs.yaml --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a files/logs/\*,\!files/logs/additional_logs.yaml --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run sudo ./uac -a live_response/process/ps.yaml --hostname uac-test-vm ${{ inputs.uac_destination_dir }}
      #  run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/ps.yaml --hostname uac-test-vm ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      - name: Run sudo ./uac -a live_response/process/ps.yaml --case-number 12345 --description "Case Description" --evidence-number 10 --examiner "Examiner Name" --notes "Case Notes" ${{ inputs.uac_destination_dir }}
        run: vagrant ssh -c "cd uac && sudo ./uac -a live_response/process/ps.yaml --case-number 12345 --description \"Case Description\" --evidence-number 10 --examiner \"Examiner Name\" --notes \"Case Notes\" ${{ inputs.uac_destination_dir }}" -- ${{ inputs.vagrant_ssh_options }}

      #- name: Run ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml
      #  run: vagrant ssh -c "cd uac && ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml" -- ${{ inputs.vagrant_ssh_options }}
