name: Run Tests

on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      unit_test_operating_system:
        required: true
        type: string
      unit_test_system_arch:
        required: true
        type: string
      unit_test_username:
        required: true
        type: string
      uac_destination_dir:
        required: true
        type: string

jobs:

  run-uac-unit-test:

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - name: Clone uac-unit-test repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac-unit-test
          path: uac-unit-test
          ref: main

      - name: Run uname -a
        run: uname -a

      - name: Run id
        run: id

      - name: Run hostname
        run: hostname

      - name: Run unit test
        run: |
          cd uac-unit-test
          ./run_test ../uac ${{ inputs.unit_test_operating_system }} ${{ inputs.unit_test_system_arch }} ${{ inputs.unit_test_username }} `hostname` tests/*

  run-uac:
    needs: run-uac-unit-test

    runs-on: ${{ inputs.runs_on }}

    steps:

      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          repository: tclahr/uac
          path: uac

      - name: Create testing profile
        run: |
          printf %b "name: test\ndescription: test\nartifacts:\n  - live_response/process/ps.yaml\n  - live_response/storage/*\n  - !live_response/storage/fs_usage.yaml" >uac/profiles/test.yaml

      - name: Run sudo ./uac -p test ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -p test ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -p test -a files/applications/viminfo.yaml ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -p test -a files/applications/viminfo.yaml ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -a live_response/process/ps.yaml ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/ps.yaml ${{ inputs.uac_destination_dir }}
      
      - name: Run sudo ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/ps.yaml,live_response/network/arp.yaml ${{ inputs.uac_destination_dir }}
      
      - name: Run sudo ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml,\!live_response/process/strings_running_processes.yaml ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/\*,\!live_response/process/hash_running_processes.yaml,\!live_response/process/procfs_information.yaml,\!live_response/process/strings_running_processes.yaml ${{ inputs.uac_destination_dir }}

      - name: Run ./uac -a live_response/process/ps.yaml -u ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/ps.yaml -u ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -a files/logs/var_log.yaml --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a files/logs/var_log.yaml --date-range-start 2022-01-01 ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -a files/logs/var_log.yaml --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a files/logs/var_log.yaml --date-range-start 2022-01-01 --date-range-end 2022-01-31 ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -a live_response/process/ps.yaml --hostname uac-test-vm ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/ps.yaml --hostname uac-test-vm ${{ inputs.uac_destination_dir }}

      - name: Run sudo ./uac -a live_response/process/ps.yaml --case-number 12345 --description "Case Description" --evidence-number 10 --examiner "Examiner Name" --notes "Case Notes" ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          sudo ./uac -a live_response/process/ps.yaml --case-number 12345 --description "Case Description" --evidence-number 10 --examiner "Examiner Name" --notes "Case Notes" ${{ inputs.uac_destination_dir }}

      - name: run ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}
        run: |
          cd uac
          ./uac -a live_response/process/ps.yaml --run-as-non-root ${{ inputs.uac_destination_dir }}

      - name: Run ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml
        run: |
          cd uac
          ./uac --validate-artifacts-file ./artifacts/live_response/process/ps.yaml
