name: Validate Artifacts File

on:
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - 'artifacts/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-artifacts-file:
    runs-on: ubuntu-latest

    steps:
      - name: Clone uac repo
        uses: actions/checkout@v3
        with:
          path: uac

      - name: Get added/modified files
        id: files
        uses: jitterbit/get-changed-files@v1
      
      - name: Validate all added/modified artifacts files
        run: |
          cd uac
          for file in ${{ steps.files.outputs.added_modified }}; do
            ./uac --validate-artifacts-file "$file"
          done

      